### ISSUE TITLE
insufficiently verbose HTTPErrors

### ISSUE THREAD

**Issue by luke-c-sargent** [TACC/agavepy#35]
In using agavepy, errors crop up (as they do during dev); often these messages are insufficient to diagnose the true problem. Example:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://agave.iplantc.org/token
```
but what part of the request is bad? looking at the error response json "error_description", we get the true cause:
```
Missing parameters: username password
```

In my own environment, I have wrapped some functions that call requests' `raise_for_status()` with a decorator that prints out relevant details before re-raising:
```
def error_catch_decorator(fn):
    def wrapper(*args, **kwargs):
        try:
            r = fn(*args, **kwargs)
        except requests.exceptions.HTTPError as error:
            err = error.response.json()
            print("HTTPError: {}\n - {}".format(err["error"], err["error_description"]))
            raise error
        return r
    return wrapper
```
I am happy to make a PR with this functionality if it would be useful; I note there are 5 calls to raise_for_status: `json_response, Token::_token, Agave::download_uri, Operation::__call__():operation` in agave.py, `json_load_url` in swagger_model.py -- should I decorate all of those functions? Is there a better approach?

**Comment by joestubbs** [comment]
Thanks very much for bringing up this issue and offering to make a PR! 

We very much like the general idea of simplifying the error handling for the client, and have toyed with some different approaches. What we have there at present is definitely insufficient and annoying. On the one hand, the most straightforward approach might be to raise a better exception object that traps the various exceptions that can occur and provides easy access to error messages. The one reluctance with that approach has always been breaking existing code that keys off specific exceptions (e.g. from requests). 

I like that your approach continues to raise an HTTPError, but I think there are a couple things we want to be careful of. First, I'm not sure we want to call print() as this won't always be helpful. In other places in the library we have used the Python logging module, so that might be an option. Also, we need to handle the case when error.response is not JSON serializable so we are not raising additional exceptions. 

It would be nice to design something that was "opt-in" from the user standpoint and/or had some hooks so that the behavior could be customized. For instance, I wonder if the decorator could check an attribute on the client to decide what to do? That attribute could default to be a no-op (so that existing behavior would not change), could be configured when instantiating the client to be a callable provided by the library, or could even be a custom callable completely provided by the user. Perhaps there could even be multiple provided by the library, including a print()er and a log()er, etc. It may not work as a decorator per se, it may have to be wrapped "by hand" so to speak. I'd have to think a little about it. 

I'd like to hear @mwvaughn's thoughts on the matter as well.

**Comment by luke-c-sargent** [comment]
i agree that `print()` is not the best solution, and that an opt-in approach seems best for backwards-compatibility and customization -- printing JSON was a bit of a kluge to get the info needed to keep on developing. good thoughts, i'll be following this thread closely! let me know how i can help, as any usability improvements to agavepy make my life easier.

**Comment by alejandrox1** [comment]
This was essentially solved in a similar manner in the develop branch.
Bad requests create a certain type of agave exception to be managed by users.

Closing stale issue.
