### ISSUE TITLE
Generating access tokens

### ISSUE THREAD

**Issue by alejandrox1** [TACC/agavepy#50]
There is no clear way of getting from the "generate an oauth client" step to the "start working with agave" step. There needs to be a clear way to generate and refresh access tokens to fill the gap.

**Comment by joestubbs** [comment]
Since the "generate an oauth client" step is really just a one time part step, does it make sense to have the user simply instantiate the Agave object again, passing the oauth client credentials as well?

What we probably want to avoid is the misconception that they need to create an oauth client each time.

Maybe the README heading "Reuse an Existing OAuth Client" should be modified to clarify that this is also the next step if you have just created an OAuth client?

**Comment by alejandrox1** [comment]
@joestubbs thank you for your comment. I'll work on rewriting those parts of the readme.
